name: Fix Code Style

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  fix-code-style:
    name: Fix Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, hash, sodium

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Check if code style fixes are needed
        id: check
        run: composer lint
        continue-on-error: true

      - name: Set fixes needed flag
        id: fixes
        run: |
          if [ "${{ steps.check.outcome }}" = "success" ]; then
            echo "fixes_needed=false" >> $GITHUB_OUTPUT
            echo "✅ No code style fixes needed"
          else
            echo "fixes_needed=true" >> $GITHUB_OUTPUT
            echo "🔧 Code style fixes needed"
          fi

      - name: Fix code style
        if: steps.fixes.outputs.fixes_needed == 'true'
        run: composer fix

      - name: Check for changes
        if: steps.fixes.outputs.fixes_needed == 'true'
        id: changes
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "changes_made=true" >> $GITHUB_OUTPUT
            echo "📝 Code style changes made:"
            git diff --name-only
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No changes made after running Pint"
          fi

      - name: Commit and push fixes
        if: steps.fixes.outputs.fixes_needed == 'true' && steps.changes.outputs.changes_made == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🎨 Fix code style with Laravel Pint

          Automatically fixed code style violations using Laravel Pint.

          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push
